FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/storage/Pics

ENV PORT=5000
EXPOSE 5000

CMD ["uvicorn", "picapi:asgi_app", "--host", "0.0.0.0", "--port", "5000"]
